from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from.import views

urlpatterns =[
    path('',views.index,name=""),
    path('index/',views.index,name="index"),
    path('adminhome/',views.adminhome,name="adminhome"),
    path('adminhead/',views.adminhead,name="adminhead"),
    path('logout/',views.logout,name="logout"),
    path('login/',views.login,name="login"),
    path('user/',views.user,name="user"),
    path('adprivacy/',views.adprivacy,name="adprivacy"),
    path('privacy/',views.privacy,name="privacy"),
    path('forestdetails/',views.forestdetails,name="forestdetails"),
    path('forest/',views.forest,name="forest"),
    path('forestlist/',views.forestlist,name="forestlist"),
    path('flora/',views.flora,name="flora"),
    path('floradetails/',views.floradetails,name="floradetails"),
    path('floralist/',views.floralist,name="floralist"),
    path('fauna/',views.fauna,name="fauna"),
    path('faunadetails/',views.faunadetails,name="faunadetails"),
    path('faunalist/',views.faunalist,name="faunalist"),
    path('news/',views.news,name="news"),
    path('newsdetails/',views.newsdetails,name="newsdetails"),
    path('newslist/',views.newslist,name="newslist"),
    path('departmenthome/',views.departmenthome,name="departmenthome"),
    path('departmenthead/',views.departmenthead,name="departmenthead"),
    path('depprivacy/',views.depprivacy,name="depprivacy"),
    path('addprogram/',views.addprogram,name="addprogram"),
    path('program/',views.program,name="program"),
    path('programlist/',views.programlist,name="programlist"),
    path('userhome/',views.userhome,name="userhome"),
    path('userhead/',views.userhead,name="userhead"),
    path('addofficer/',views.addofficer,name="addofficer"),
    path('officerlist/',views.officerlist,name="officerlist"),
    path('depnews/',views.depnews,name="depnews"),
    path('usrnews/',views.usrnews,name="usrnews"),
    path('applypass/',views.applypass,name="applypass"),
    path('apply/',views.apply,name="apply"),
    path('producttype/',views.producttype,name="producttype"),
    path('category/',views.category,name="category"),
    path('product/',views.product,name="product"),
    path('deleteforest/',views.deleteforest,name="deleteforest"),
    path('editforest/',views.editforest,name="editforest"),
    path('deletenews/',views.deletenews,name="deletenews"),
    path('editnews/',views.editnews,name="editnews"),
    path('categorylist/',views.categorylist,name="categorylist"),
    path('deletecat/',views.deletecat,name="deletecat"),
    path('editcat/',views.editcat,name="editcat"),
    path('deleteflora/',views.deleteflora,name="deleteflora"),
    path('editflora/',views.editflora,name="editflora"),
    path('deletefauna/',views.deletefauna,name="deletefauna"),
    path('editfauna/',views.editfauna,name="editfauna"),
    path('productlist/',views.productlist,name="productlist"),
    path('pro',views.pro,name="pro"),
    path('deleteproduct',views.deleteproduct,name="deleteproduct"),
    path('editproduct',views.editproduct,name="editproduct"),
    path('usrprivacy',views.usrprivacy,name="usrprivacy"),
    path('shop',views.shop,name="shop"),
    path('payment',views.payment,name="payment"),
    path('pay',views.pay,name="pay"),
    path('usrforest',views.usrforest,name="usrforest"),
    path('usrprofile',views.usrprofile,name="usrprofile"),
    path('editprofile',views.editprofile,name="editprofile"),
]