# Generated by Django 3.2.13 on 2022-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
                ('role', models.CharField(max_length=25, verbose_name='role')),
            ],
        ),
    ]
