# Generated by Django 3.2.13 on 2022-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20220419_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='forest',
            fields=[
                ('forestid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('area', models.CharField(max_length=100, verbose_name='area')),
                ('district', models.CharField(max_length=50, verbose_name='district')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('attraction', models.CharField(max_length=200, verbose_name='attraction')),
                ('website', models.CharField(max_length=50, verbose_name='website')),
            ],
        ),
    ]
