# Generated by Django 3.2.13 on 2022-04-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_forest'),
    ]

    operations = [
        migrations.CreateModel(
            name='flora',
            fields=[
                ('floraid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('botanical', models.CharField(max_length=100, verbose_name='botanical')),
                ('habitat', models.CharField(max_length=100, verbose_name='habitat')),
                ('vegetation', models.CharField(max_length=100, verbose_name='vegetation')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('photo', models.FileField(upload_to='images/', verbose_name='photo')),
                ('forest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.forest')),
            ],
        ),
    ]
