# Generated by Django 3.2.13 on 2022-04-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_awareness_program_fauna_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrypass',
            fields=[
                ('entrypassid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=100, verbose_name='date')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('forest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.forest')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.user')),
            ],
        ),
    ]
