# Generated by Django 3.2.12 on 2022-04-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20220424_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('uses', models.CharField(max_length=300, verbose_name='uses')),
                ('quantity', models.CharField(max_length=100, verbose_name='quantity')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('image', models.FileField(upload_to='images/', verbose_name='image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.category')),
            ],
        ),
    ]
