# Generated by Django 3.2.13 on 2022-04-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=100, verbose_name='date')),
                ('amount', models.DateField(max_length=100, verbose_name='amount')),
                ('cardtype', models.DateField(max_length=100, verbose_name='cardtype')),
                ('cardno', models.DateField(max_length=100, verbose_name='cardno')),
                ('cvv', models.DateField(max_length=100, verbose_name='cvv')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.user')),
            ],
        ),
    ]
