# Generated by Django 3.2.13 on 2022-04-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('email', models.CharField(max_length=20, verbose_name='email')),
                ('mobileno', models.CharField(max_length=20, verbose_name='mobileno')),
                ('profile', models.FileField(upload_to='images/', verbose_name='profile')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.login')),
            ],
        ),
    ]
