# Generated by Django 3.2.13 on 2022-04-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_flora'),
    ]

    operations = [
        migrations.CreateModel(
            name='awareness_program',
            fields=[
                ('programid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('cname', models.CharField(max_length=100, verbose_name='cname')),
                ('date', models.DateField(max_length=100, verbose_name='date')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('date', models.DateField(max_length=100, verbose_name='date')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='fauna',
            fields=[
                ('faunaid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('habitat', models.CharField(max_length=100, verbose_name='habitat')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('photo', models.FileField(upload_to='images/', verbose_name='photo')),
                ('forest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.forest')),
            ],
        ),
    ]
