# Generated by Django 3.2.13 on 2022-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_entrypass'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
        migrations.AlterField(
            model_name='flora',
            name='photo',
            field=models.FileField(upload_to='images/', verbose_name='photo:'),
        ),
    ]
