# Generated by Django 3.2.13 on 2022-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='police',
            fields=[
                ('policeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('idno', models.CharField(max_length=100, verbose_name='idno')),
                ('designation', models.CharField(max_length=100, verbose_name='designation')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('contactno', models.CharField(max_length=100, verbose_name='contactno')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardno',
            field=models.CharField(max_length=100, verbose_name='cardno'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardtype',
            field=models.CharField(max_length=100, verbose_name='cardtype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=100, verbose_name='cvv'),
        ),
    ]
